### 1. Import NumPy and Print Version

In [4]:
import numpy as np
print(f"Version of NumPy is {np.__version__}.")

Version of NumPy is 2.3.5.


### 2. 1D Array

In [5]:
one_d_arr = np.array(range(0, 10))
print(one_d_arr)

[0 1 2 3 4 5 6 7 8 9]


### 3. Bollean Arrray

In [7]:
bol_arr = np.full((3, 3), True)
print(bol_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 4. Extract Odd Numbers

In [8]:
arr = np.array(range(0, 10))
print(arr[arr % 2 != 0])

[1 3 5 7 9]


### 5. Replace Odd Numbers with -1

In [11]:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 6. Reshape 1D Array to 2D Array

In [13]:
arr = np.array(range(1, 11))
two_d_arr = arr.reshape((2, 5))
print(two_d_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 7. Stacking Array Vertically

In [14]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

vstack = np.vstack([v1, v2])
print(vstack)

[[1 2 3]
 [4 5 6]]


### 8. Identity Matrix

In [21]:
id_mat = np.identity(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 9. Generate Array with Random Number

In [22]:
arr = np.random.rand(10)
print(arr)

[0.22011904 0.16828804 0.03188579 0.38871596 0.13208292 0.17252317
 0.1295438  0.40321383 0.41281572 0.68530259]


### 10. Generate Linspace

In [23]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### 11. Common Items between Two Arrays 

In [26]:
a = np.array([2, 4, 6])
b = np.array([3, 6])
c = np.intersect1d(a, b)
print(c)

[6]


### 12. Mathced Indices from Two Arrays

In [28]:
a = np.array([2, 6, 6, 12])
b = np.array([3, 6, 9, 12])
matched = np.where(a == b)
print(matched)

(array([1, 3]),)


### 13. Filter Data from Range

In [29]:
a = np.array([12, 42, 41, 21, 34, 23, 423, 1, 422, 34, 53, 78, 37])
print(a[((a > 20) & (a < 100))])

[42 41 21 34 23 34 53 78 37]


## 14. Broadcasting Row Subtraction

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_mean = np.mean(arr, axis=1, keepdims=True)
new_arr = arr - arr_mean
print(arr)
print(arr_mean)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### 15. Sorting by Column

In [42]:
sort_idx = arr[:, 1].argsort()
sorted_array = arr[sort_idx]
print(sorted_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 16. Reversing Array

In [47]:
arr = np.arange(9).reshape(3, 3)
reversed_arr = arr[::-1]
print(reversed_arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### 17. Scientific Notation

In [50]:
np.random.seed(100)
rand_arr = np.random.random([3, 3])
np.set_printoptions(precision=3, suppress=True)
print(rand_arr)

[[0.543 0.278 0.425]
 [0.845 0.005 0.122]
 [0.671 0.826 0.137]]


### 18. Dot Product

In [53]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)
dot_product = np.dot(A, B)
dot_product = A @ B
print(dot_product)

[[22 28]
 [49 64]]


### 19. Aggregation 

In [54]:
data = np.array([1, 5, 10, 15, 20])
mean_val = np.mean(data)
median_val = np.median(data)
std_val = np.std(data)
print(mean_val, median_val, std_val)

10.2 10.0 6.794115100585212


### 20. Normalization (Standardization)

In [56]:
X = np.random.random((5, 5))
x_mean = np.mean(X)
x_std = np.std(X)
norm_arr = (X - x_mean) / x_std
print(norm_arr)

[[-1.445  1.265  1.552 -1.371  1.265]
 [ 0.27   0.795  0.439  0.286 -1.496]
 [-0.895  0.168  0.88  -0.765 -0.654]
 [ 1.144  1.533  1.247 -0.42   0.34 ]
 [-0.435 -0.481 -0.996 -0.807 -1.419]]


### 21. Missing Values

In [68]:
arr = np.random.random((10, 10))
row_idx = np.random.randint(0, 10, 5)
col_idx = np.random.randint(0, 10, 5)
arr[row_idx, col_idx] = np.nan

print(np.isnan(arr).sum())

5


### 22. Drop Missing Values

In [77]:
arr = np.array([1, 4, 2, 5, np.nan, 8, np.nan, 11])
new_arr = arr[~np.isnan(arr)]

print(new_arr)

[ 1.  4.  2.  5.  8. 11.]


### 23. Euclidean Distance

In [80]:
a = np.arange(1, 4)
b = np.arange(4, 7)
dist_manual = np.sqrt(np.sum((a - b)**2))
dist_numpy = np.linalg.norm(a - b)
print(dist_manual)
print(dist_numpy)

5.196152422706632
5.196152422706632


### 24. Argmax (Predictions) 

In [86]:
arr = np.arange(1, 10).reshape(3, 3)
pred = np.argmax(arr, axis=1)
print(pred)
print(arr)

[2 2 2]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 25. One-Hot Encoding

In [100]:
arr = np.array([0, 1, 2, 1, 0])
num_classes = 3
one_hot = np.eye(num_classes)[arr]

print(one_hot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


### 26. Class Balancing

In [103]:
arr = np.array([0, 0, 0, 1, 0, 1, 1, 2, 0, 1])
unique, counts = np.unique(arr, return_counts=True)

print(np.column_stack((unique, counts)))

[[0 5]
 [1 4]
 [2 1]]


### 27. Image Padding

In [108]:
arr = np.ones((3, 3))
padded_arr = np.pad(arr, pad_width=1, mode="constant", constant_values=0)
print(padded_arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 28. Top K Values

In [119]:
arr = np.array([10, 5, 2, 15, 20, 1, 50, 2, 75, 3])
k = 3
top_k = np.partition(arr, k)[-k:]

print(top_k)

[20 50 75]


### 29. Rolling Mean

In [122]:
arr = np.arange(1, 7)
window_size = 3
window = np.ones(window_size) / window_size
moving_avg = np.convolve(arr, window, mode="valid")

print(moving_avg)
print(window)

[2. 3. 4. 5.]
[0.333 0.333 0.333]


### 30. Eigenvalues (PCA)

In [123]:
matrix = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[5. 2.]
[[ 0.894 -0.707]
 [ 0.447  0.707]]
