In [2]:
# Import NumPy
import numpy as np

# NumPy Exercises

In [3]:
# Create array from 1 to 50 and reshpae it (5, 10)
arr = np.arange(1, 51).reshape(5, 10)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [6]:
# Compute sum, mean, and standard deviation
sum = np.sum(arr)
mean = np.mean(arr)
std = np.std(arr)

print(f"Sum of the Array is {sum}")
print(f"Average of the Array is {mean}")
print(f"Standard Deviation of the Array is {std.round(2)}")

Sum of the Array is 1275
Average of the Array is 25.5
Standard Deviation of the Array is 14.43


In [7]:
# Slice first three rows
new_arr = arr[:3]

print(new_arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [8]:
# Multiply all values by two
new_arr = arr * 2

print(new_arr)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]
